# Generated by Django 2.0.1 on 2018-05-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('provinence', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('district_county_town', models.CharField(blank=True, max_length=10)),
                ('neighborhood_township_village', models.CharField(max_length=10)),
                ('address', models.TextField(blank=True)),
                ('escape_room', models.IntegerField()),
            ],
        ),
    ]
