# Generated by Django 2.0.1 on 2018-05-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20180515_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('provinence', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('district_county_town', models.CharField(blank=True, max_length=10)),
                ('neighborhood_township_village', models.CharField(max_length=10)),
                ('address', models.TextField(blank=True)),
                ('x_axis', models.CharField(max_length=20)),
                ('y_axis', models.CharField(max_length=20)),
                ('location_class', models.CharField(max_length=20)),
                ('location_grade', models.CharField(max_length=20)),
                ('escape_room', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='LocationTag',
            new_name='MarketingAreaTag',
        ),
    ]
