# Generated by Django 2.0.1 on 2018-05-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20180530_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='subwaystation',
            name='provience',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subwaystation',
            name='station_category',
            field=models.ManyToManyField(to='location.StationCategory'),
        ),
        migrations.AddField(
            model_name='subwaystation',
            name='title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketingarea',
            name='comsumption_propensity',
            field=models.CharField(choices=[('ENTERTAINMENT', '유흥'), ('DATING', '데이트'), ('OVERALL', '종합'), ('SHOPPING', '쇼핑')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketingarea',
            name='location_class',
            field=models.CharField(choices=[('UV', '대학'), ('TF', '교통'), ('LV', '주거'), ('OF', '오피스')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketingarea',
            name='location_grade',
            field=models.CharField(choices=[('A', 'A'), ('C', 'C'), ('B', 'B'), ('S', 'S')], max_length=20),
        ),
    ]
