# Generated by Django 2.0.1 on 2018-05-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20180530_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingarea',
            name='comsumption_propensity',
            field=models.CharField(choices=[('OVERALL', '종합'), ('DATING', '데이트'), ('ENTERTAINMENT', '유흥'), ('SHOPPING', '쇼핑')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketingarea',
            name='location_grade',
            field=models.CharField(choices=[('C', 'C'), ('S', 'S'), ('B', 'B'), ('A', 'A')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subwaystation',
            unique_together={('title', 'provience')},
        ),
    ]
