# Generated by Django 2.0.1 on 2018-05-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20180530_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='distnace_three',
            new_name='distance_three',
        ),
        migrations.AlterField(
            model_name='marketingarea',
            name='comsumption_propensity',
            field=models.CharField(choices=[('DATING', '데이트'), ('SHOPPING', '쇼핑'), ('OVERALL', '종합'), ('ENTERTAINMENT', '유흥')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketingarea',
            name='location_class',
            field=models.CharField(choices=[('OF', '오피스'), ('TF', '교통'), ('UV', '대학'), ('LV', '주거')], max_length=20),
        ),
    ]
