# Generated by Django 2.0.1 on 2018-05-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20180530_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingarea',
            name='location_class',
            field=models.CharField(choices=[('OF', '오피스'), ('UV', '대학'), ('LV', '주거'), ('TF', '교통')], max_length=20),
        ),
    ]
