# Generated by Django 2.0.1 on 2018-05-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_auto_20180530_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='subwaystation',
            name='category',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subwaystation',
            name='title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketingarea',
            name='comsumption_propensity',
            field=models.CharField(choices=[('DATING', '데이트'), ('ENTERTAINMENT', '유흥'), ('OVERALL', '종합'), ('SHOPPING', '쇼핑')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketingarea',
            name='location_class',
            field=models.CharField(choices=[('OF', '오피스'), ('LV', '주거'), ('UV', '대학'), ('TF', '교통')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketingarea',
            name='location_grade',
            field=models.CharField(choices=[('A', 'A'), ('C', 'C'), ('S', 'S'), ('B', 'B')], max_length=20),
        ),
    ]
