# Generated by Django 2.0.1 on 2018-05-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_auto_20180530_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20)),
                ('distance_one', models.ManyToManyField(related_name='univ_distance_one', to='location.SubwayStation')),
                ('distance_two', models.ManyToManyField(related_name='univ_distance_two', to='location.SubwayStation')),
                ('distance_zero', models.ManyToManyField(related_name='univ_distance_zero', to='location.SubwayStation')),
                ('distnace_three', models.ManyToManyField(related_name='univ_distance_three', to='location.SubwayStation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='marketingarea',
            name='comsumption_propensity',
            field=models.CharField(choices=[('DATING', '데이트'), ('ENTERTAINMENT', '유흥'), ('SHOPPING', '쇼핑'), ('OVERALL', '종합')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketingarea',
            name='location_class',
            field=models.CharField(choices=[('LV', '주거'), ('TF', '교통'), ('UV', '대학'), ('OF', '오피스')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketingarea',
            name='location_grade',
            field=models.CharField(choices=[('B', 'B'), ('A', 'A'), ('C', 'C'), ('S', 'S')], max_length=20),
        ),
    ]
