# Generated by Django 2.0.1 on 2018-05-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_auto_20180530_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='subwaystation',
            name='category',
        ),
        migrations.AlterField(
            model_name='marketingarea',
            name='location_class',
            field=models.CharField(choices=[('OF', '오피스'), ('UV', '대학'), ('TF', '교통'), ('LV', '주거')], max_length=20),
        ),
        migrations.AddField(
            model_name='subwaystation',
            name='station_category',
            field=models.ManyToManyField(to='location.StationCategory'),
        ),
    ]
