# Generated by Django 2.0.1 on 2018-05-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20180530_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='subwaystation',
            name='provience',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketingarea',
            name='comsumption_propensity',
            field=models.CharField(choices=[('SHOPPING', '쇼핑'), ('OVERALL', '종합'), ('ENTERTAINMENT', '유흥'), ('DATING', '데이트')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketingarea',
            name='location_class',
            field=models.CharField(choices=[('TF', '교통'), ('LV', '주거'), ('UV', '대학'), ('OF', '오피스')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketingarea',
            name='location_grade',
            field=models.CharField(choices=[('C', 'C'), ('A', 'A'), ('B', 'B'), ('S', 'S')], max_length=20),
        ),
    ]
