# Generated by Django 2.0.1 on 2018-05-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_auto_20180530_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingarea',
            name='comsumption_propensity',
            field=models.CharField(choices=[('DATING', '데이트'), ('OVERALL', '종합'), ('SHOPPING', '쇼핑'), ('ENTERTAINMENT', '유흥')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketingarea',
            name='location_grade',
            field=models.CharField(choices=[('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subwaystation',
            unique_together={('title', 'provience')},
        ),
    ]
