# Generated by Django 2.0.1 on 2018-02-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesales',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
