# Generated by Django 2.0.1 on 2018-02-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20180223_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesales',
            name='count',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='timesales',
            name='sales',
            field=models.IntegerField(blank=True),
        ),
    ]
