# Generated by Django 2.0.1 on 2018-02-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20180225_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesales',
            name='count',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timesales',
            name='sales',
            field=models.IntegerField(null=True),
        ),
    ]
