# Generated by Django 2.0.1 on 2018-02-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_dailysales'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysales',
            name='weekday',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='kiosk_cash_saels',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='kiosk_cash_sales',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='pos_card_sales',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='pos_cash_sales',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='total_sales',
            field=models.IntegerField(null=True),
        ),
    ]
