# Generated by Django 2.0.1 on 2018-02-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20180226_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysales',
            old_name='kiosk_cash_saels',
            new_name='kiosk_card_sales',
        ),
    ]
