# Generated by Django 2.0.1 on 2018-02-27 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20180226_0815'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailysales',
            unique_together={('store', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='timesales',
            unique_together={('store', 'time')},
        ),
    ]
