# Generated by Django 2.0.1 on 2018-02-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20180227_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverSearching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.CharField(choices=[('hd1', '홍대 1호점'), ('hd2', '홍대 2호점'), ('sc', '신촌점'), ('bp', '부평점'), ('sw', '수원역점'), ('sh', '서현점')], max_length=10, verbose_name='매장')),
                ('date', models.DateField()),
                ('keyword', models.CharField(max_length=20)),
                ('occupied', models.CharField(max_length=300)),
                ('percent_first_page', models.CharField(max_length=10)),
                ('percent_for_all', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '네이버 블로그 검색 결과',
                'verbose_name_plural': '네이버 블로그 검색 결과',
            },
        ),
    ]
