# Generated by Django 2.0.1 on 2018-02-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_naversearching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naversearching',
            name='percent_first_page',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='naversearching',
            name='percent_for_all',
            field=models.FloatField(max_length=10),
        ),
    ]
