# Generated by Django 2.0.1 on 2018-02-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20180228_1221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='naversearching',
            unique_together={('store', 'date', 'keyword')},
        ),
    ]
