# Generated by Django 2.0.1 on 2018-04-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20180228_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='naversearching',
            name='is_mobile',
            field=models.BooleanField(default=0),
        ),
    ]
