# Generated by Django 2.0.1 on 2018-04-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20180421_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='naversearching',
            name='is_blog_only',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='naversearching',
            unique_together={('store', 'date', 'keyword', 'is_mobile', 'is_blog_only')},
        ),
    ]
