# Generated by Django 2.0.1 on 2018-02-14 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('supply_price', models.IntegerField()),
                ('delivery_price', models.IntegerField()),
                ('available_stock', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_stock', models.IntegerField()),
                ('supplier', models.CharField(blank=True, max_length=20)),
                ('user_agent', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=100, validators=[inventory.validators.min_length_2_validator])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=models.SET(1), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Item_Category'),
        ),
    ]
