# Generated by Django 2.0.1 on 2018-02-26 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supply_price', models.IntegerField()),
                ('delivery_price', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '주문한 제품',
                'verbose_name_plural': '주문한 제품',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supply_price', models.IntegerField()),
                ('delivery_price', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('available_stock', models.IntegerField()),
                ('recommended_stock', models.IntegerField()),
                ('supplier', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_category',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', '주문 진행 중'), ('cancelled', '주문 취소됨'), ('order-complete', '발주 완료'), ('deliverying', '배송중'), ('delivered', '배송완료'), ('complete', '정상수령'), ('returned', '반품수거'), ('missing', '주문누락')], default='processing', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Item_Category',
        ),
        migrations.AddField(
            model_name='product',
            name='item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Product_Category'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Order', verbose_name='주문서'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product', verbose_name='제품'),
        ),
    ]
