# Generated by Django 2.0.1 on 2018-02-07 14:23

from django.db import migrations, models
import inventory.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.CharField(max_length=100, validators=[inventory.validators.min_length_2_validator]),
        ),
    ]
