# Generated by Django 2.0.1 on 2018-02-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='age',
            field=models.IntegerField(choices=[(10, '-12'), (15, '12-19'), (21, '20-23'), (25, '23-28U(대학생)'), (26, '23-28E(직장인)'), (32, '28+'), (38, '35+')], default=25),
        ),
        migrations.AlterField(
            model_name='survey',
            name='type',
            field=models.CharField(choices=[('MF', 'MALE+FEMALE'), ('FF', 'FEMALE+FEMALE'), ('MM', 'MALE+MALE'), ('M+', 'MALE+'), ('F+', 'FEMALE+'), ('FAM', 'FAMILY'), ('G3+', 'GROUP3+'), ('G5+', 'GROUP5+')], default='MF', max_length=20),
        ),
    ]
